#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

login:
  path: /login
  controller: App\Controller\AuthController::login
  methods: POST

api_login_check:
  path: /api/login_check
